name: Aks deploy
on: 
 workflow_dispatch:
   inputs:
     image:
      description: 'image'
      required: true
      default: 'first'
   
env:
  CLUSTER_NAME: blackbird1
  CLUSTER_RESOURCE_GROUP: Test
  NAMESPACE: default
  REPO: blackbirdaks
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Install build
    - name: build
      uses: azure/docker-login@v1
      with: 
       creds: ${{ secrets.AZURE_CREDENTIALS }}
       REPO: ${{ env.REPO }}
    - run: |
         #az acr build --image app:latest --registry ${{ env.REPO }} --file Dockerfile .
         docker build . -t ${{ env.REPO }}/${{ github.event.inputs.image }}:${{ github.sha }
         docker push ${{ env.REPO }}/${{ github.event.inputs.image }}:${{ github.sha }}
         #docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ github.event.inputs.image }}:${{ github.sha }}
         #docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ github.event.inputs.image }}:${{ github.sha }}

    # Install hel
   # - name: Install Helm
    #  run: |
     #   curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
        
   # - name: 'deploy'
     # env:
       # CLUSTER_RESOURCE_GROUP_NAME: ${{ env.CLUSTER_RESOURCE_GROUP }}
       # CLUSTER_NAME: ${{ env.CLUSTER_NAME }}
     # run: |
       # az aks get-credentials \
        #  --resource-group $CLUSTER_RESOURCE_GROUP \
         # --name $CLUSTER_NAME \
         # --overwrite-existing
        #helm upgrade -i vote-app azure-vote-front/ --set image.repository=${{ env.REPO }}.azurecr.io/app --set image.tag=latest --wait
        #kubectl get services -o wide
        
