on: [push]
env:
  CLUSTER_NAME: blackbird1
  CLUSTER_RESOURCE_GROUP: Test
  NAMESPACE: default-1
  REPO: blackbirdaks
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Install build
    - name: build
      run: |
        az acr build --image app:latest --registry ${{ env.REPO }} --file Dockerfile .

    # Install helm
   # - name: Install Helm
    #  run: |
     #   curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
        
    - name: 'deploy'
      env:
        CLUSTER_RESOURCE_GROUP_NAME: ${{ env.CLUSTER_RESOURCE_GROUP }}
        CLUSTER_NAME: ${{ env.CLUSTER_NAME }}
      run: |
        az aks get-credentials \
          --resource-group $CLUSTER_RESOURCE_GROUP \
          --name $CLUSTER_NAME \
          --overwrite-existing
        helm upgrade -i vote-app azure-vote-front/ --set image.repository=${{ env.REPO }}.azurecr.io/app --set image.tag=latest --wait
        kubectl get services -o wide
        
