
on: [push]

name: AzureLoginSample
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.AZURE_CREDENTIALS }}
        run: |
          echo "$SUPER_SECRET"
